### ISSUE TITLE
Feature request: Developer dependencies

### ISSUE THREAD

**Issue by mcandre** [nektro/zigmod#3]
Hey, I'd like to see an option for specifying dependencies that aren't needed regarding runtime, but serve to help build Zig projects. For example, linters, code generators, and testing frameworks. Sometimes these call for developer executables, too. Which need to be managed in `$PATH` on a per project basis.

Could we get something like Bundler / NPM developer dependencies?

**Comment by nektro** [comment]
This will probably be done by changing `deps.packages` from a `[]std.build.Pkg` to a struct, so that you could reference them by name ie `deps.packages.my_linter`. And since Zig lazily builds code, any package not used in your app directly through an `@import` would not get added to your executables.

**Comment by nektro** [comment]
actually I'm going to keep `deps.packages` as a `[]std.build.Pkg` to maintain compatibility and add `deps.pkgs` as the struct to allow for this feature as well as seamless interop between zkg and zigmod on a `build.zig` level.
