### ISSUE TITLE
Allow symlink of packages

### ISSUE THREAD

**Issue by locriacyber** [nektro/zigmod#49]
This is useful when developing packages. This is like `yarn link`.

CLI command `zigmod link <name> <local dir>` and `unlink` would be used to override package with local version. A config file at "~/.config/zigmod/links.yml" would store the config.

**Comment by nektro** [comment]
Since Zigmod is designed to be fairly decentralized, the concept of just names don't hold as much sense as they do in a npm/crates universe. The recommended workflow for the local development of packages is laid out here https://github.com/nektro/zigmod/blob/master/docs/tutorial.md#contributing-to-dependency-upstream. If the subpackage you're working on is your own, the flow is even more streamlined as you do not have to make a fork.

**Comment by locriacyber** [comment]
But I want to work locally. Now I have to manually symlink the local directory to the one zigmod uses.

**Comment by nektro** [comment]
the folder path i described above is local

**Comment by locriacyber** [comment]
By "local" I mean "on my machine".

**Comment by nektro** [comment]
yes

**Comment by jacmoe** [comment]
Oh, I understand: tell Zigmod that the package is a git hosted dependency, let it fetch it, and then work on it from the `.zigmod/deps/git` directory (after adding a remote)

That's similar to how I would work with PHP Composer packages.

Perhaps put this somewhere easily accessible in the docs? It's a common thing to want to do :)
